name: Publish

on:
  workflow_dispatch: {}
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'
      - run: yarn --frozen-lockfile
      - run: yarn test
      - run: npm publish --access publish
